In [1]:
#读取X.pickle和y.pickle文件，分别传递到特征项X和目标项y变量
import pickle
X = pickle.load(open("X.pickle", "rb"))
y = pickle.load(open("y.pickle", "rb"))

In [2]:
#导入相关的包
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [4]:
X_new = X.reshape(-1, X.shape[1] * X.shape[2])  #将特征项X的所有特征展平为一维
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.2, random_state=42)   #将特征项X和目标相y拆分为训练集和测试集

In [21]:
#用训练集训练KNN模型
knn = KNeighborsClassifier(n_neighbors=10, metric='euclidean', p = 7)
knn.fit(X_train, y_train)
pred_knn = knn.predict(X_test)
#查看模型的效果
print(classification_report(y_test, pred_knn))
print(confusion_matrix(y_test, pred_knn))

              precision    recall  f1-score   support

           0       0.21      0.20      0.20       248
           1       0.30      0.29      0.29       376
           2       0.31      0.11      0.17       255
           3       0.20      0.43      0.27       240
           4       0.28      0.19      0.23       299
           5       0.23      0.24      0.23       227

    accuracy                           0.24      1645
   macro avg       0.26      0.24      0.23      1645
weighted avg       0.26      0.24      0.24      1645

[[ 49  49  16  71  32  31]
 [ 53 108  23 105  44  43]
 [ 39  59  29  69  36  23]
 [ 32  35   8 104  18  43]
 [ 40  51  12 101  56  39]
 [ 21  61   5  74  12  54]]


In [14]:
#用训练集训练随机森林模型
rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(X_train, y_train)
pred_rfc = rfc.predict(X_test)
#查看模型的效果
print(classification_report(y_test, pred_rfc))
print(confusion_matrix(y_test, pred_rfc))

              precision    recall  f1-score   support

           0       0.44      0.28      0.34       248
           1       0.27      0.38      0.32       376
           2       0.42      0.36      0.39       255
           3       0.35      0.46      0.39       240
           4       0.47      0.33      0.39       299
           5       0.30      0.30      0.30       227

    accuracy                           0.35      1645
   macro avg       0.37      0.35      0.35      1645
weighted avg       0.37      0.35      0.35      1645

[[ 70  69  29  49  25   6]
 [ 21 141  34  43  35 102]
 [ 31  74  91  29  21   9]
 [ 12  41  34 110  24  19]
 [ 22  88  23  46  99  21]
 [  4 102   6  40   8  67]]


In [14]:
#用训练集训练SVC模型
clf = SVC()
clf.fit(X_train, y_train)
pred_clf = clf.predict(X_test)
#查看模型的效果
print(classification_report(y_test, pred_clf))
print(confusion_matrix(y_test, pred_clf))

              precision    recall  f1-score   support

           0       0.40      0.16      0.23       248
           1       0.31      0.60      0.41       376
           2       0.48      0.27      0.35       255
           3       0.29      0.38      0.33       240
           4       0.41      0.32      0.36       299
           5       0.44      0.27      0.33       227

    accuracy                           0.35      1645
   macro avg       0.39      0.33      0.34      1645
weighted avg       0.38      0.35      0.34      1645

[[ 40 104  17  48  30   9]
 [ 17 227  25  46  39  22]
 [ 17 100  69  33  29   7]
 [  9  78  19  91  23  20]
 [ 12 111   9  51  95  21]
 [  6 103   4  40  13  61]]
